#!/bin/bash
# Run a paper test
#
# Copyright (c) 2021 Reuben Thomas <rrt@sc3d.org>
#
# This file is part of Paper.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <https://www.gnu.org/licenses/>.

set -e

test_file="$1"
name="${1%.sh}"
basename=$(basename $name)
test_dir="$(pwd)/$basename.$$"

# Test runners.
# Arguments are command to run.
function no_output_test() {
    eval "$@" > "tests/$basename-output.txt"
}

function test() {
    no_output_test "$@"
    diff -u "$srcdir/$basename-expected.txt" "tests/$basename-output.txt"
}

# Make a test installation of paper
cd ..
make install DESTDIR="$test_dir"
cd "$test_dir"

# Run the test script.
source $test_file
